services:
  kv-wsrelay:
    build:
      context: ./kv-wsrelay
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - LOG_LEVEL=info
      - CORS_ALLOW_ORIGINS=*
      - CORS_ALLOW_CREDENTIALS=false
      - CORS_MAX_AGE=600
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
