services:
  kv-wsrelay:
    build:
      context: ./kv-wsrelay
      dockerfile: Dockerfile
      target: production
    environment:
      - REDIS_ADDR=redis:6379
      - LOG_LEVEL=info
      - CORS_ALLOW_ORIGINS=*
      - CORS_ALLOW_CREDENTIALS=false
      - CORS_MAX_AGE=600
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - kv-wsrelay
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
